language: java
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY_ID
  region: eu-west-2
  app: My First Elastic Beanstalk Application
  zip_file: target/questfor92.war
  env: questfor92
  bucket_name: elasticbeanstalk-eu-west-2-307854530528
  on:
    repo: grandjambon/questfor92
    branch: master
